# Generated by Django 5.0.4 on 2024-05-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
